export const BLOG_TAGS = [
    'Technology',
    'Design',
    'Development',
    'Marketing',
    'Business',
    'Finance',
    'Health',
    'Education',
    'Science',
    'Art',
    'Music',
    'Travel',
    'Food',
]